-- INSERIR DADOS PARA TESTE

INSERT INTO TB_CONTA(ID, NAME_OWNER, LAST_NAME_OWNER, AGENCY_CODE, NUMBER_ACCOUNT, DIGIT_VERIFICATION) 
              VALUES(1, 'Leonardo', 'Rodrigues', '2345', '87645698', '0'); 
              
INSERT INTO TB_CONTA(ID, NAME_OWNER, LAST_NAME_OWNER, AGENCY_CODE, NUMBER_ACCOUNT, DIGIT_VERIFICATION)
              VALUES(2, 'Fabia', 'Souza', '1234', '98765432', '1'); 

             

-- CREATE TABLE TB_CONTA(
-- ID BIGINT NOT NULL AUTO_INCREMENT,
-- NAME_OWNER VARCHAR(50) NOT NULL,
-- AGENCY_CODE VARCHAR(4) NOT NULL,
-- NUMBER_ACCOUNT VARCHAR(8) NOT NULL,
-- DIGIT_VERIFICATION VARCHAR(3) NOT NULL,
-- REGISTER_ID VARCHAR(20) NOT NULL,
-- UNIQUE (NUMBER_ACCOUNT),
-- UNIQUE (REGISTER_ID),
-- PRIMARY KEY (ID)
--);

